# 목적

- 텐서플로우 기본 사용법 익히기

# 기본틀
- 그래프
- 연산 처리

In [1]:
import tensorflow as tf
%tensorflow_version 1.x

In [3]:
# 관계 기술 => 그래프 => flow 구성
hello = tf.constant('hello DL!!')
hello

<tf.Tensor 'Const:0' shape=() dtype=string>

In [4]:
# 구동
# 1. 세션 오픈
sess = tf.Session()
# 2. 데이터를 주입하여 연산
print(sess.run(hello))
# 3. 세션 클로즈
sess.close()

b'hello DL!!'

In [7]:
with tf.Session() as sess:
  print(sess.run(hello))

b'hello DL!!'


# 텐서플로우를 이용한 간단한 연산

In [8]:
# 1. flow 구성
# 상수 정의
a = tf.constant(123)
b = tf.constant(500)
a, b

(<tf.Tensor 'Const_1:0' shape=() dtype=int32>,
 <tf.Tensor 'Const_2:0' shape=() dtype=int32>)

In [0]:
# 연산 형태 정의
add_operation = a + b 

In [11]:
# 실제 연산 처리(구동)
with tf.Session() as sess:
  res = sess.run(add_operation)
  print(res, type(res))

623 <class 'numpy.int32'>


# 텐서플로우의 기본 항목 사용
- 핵심 데이터 구조
  1. 상수: Constant
  2. 변수: Variable
  3. 플레이스홀더: Placeholder

In [13]:
# 상수 정의
a = tf.constant(100, name='a')
b = tf.constant(110, name='b')
c = tf.constant(120, name='c')
a,b,c

(<tf.Tensor 'a:0' shape=() dtype=int32>,
 <tf.Tensor 'b:0' shape=() dtype=int32>,
 <tf.Tensor 'c:0' shape=() dtype=int32>)

In [14]:
# 변수 정의
v = tf.Variable(0, name='v')
v, v.name

(<tf.Variable 'v:0' shape=() dtype=int32_ref>, 'v:0')

In [0]:
# 연산(데이터 플로우 그래프) 정의
calc_operation = a + b + c

In [16]:
assign_operation = tf.assign(v, calc_operation)
assign_operation

<tf.Tensor 'Assign:0' shape=() dtype=int32_ref>

In [17]:
with tf.Session() as sess:
  res = sess.run(assign_operation)
  print(res, type(res))
  res = sess.run(v)
  print(res, type(res))

330 <class 'numpy.int32'>
330 <class 'numpy.int32'>


## 플레이스 홀더
  - 템플릿같은 느낌
  - 데이터 플로우 그래프를 구축 시 값을 담는 형태만 정의
  - 세션 수행 시 데이터가 담긴다(함수 호출 시 인자를 받는 파라미터 같은 것)

In [0]:
# 플레이스홀더
# 정수값 3개가 올 수 있다
p = tf.placeholder(tf.int32, [3])
# 상수
c = tf.constant(2)
# 벡터 * 스칼라
x2_op = p * c

In [21]:
with tf.Session() as sess:
  res = sess.run(x2_op, feed_dict={p:[1,2,3]})
  print(res, type(res))

[2 4 6] <class 'numpy.ndarray'>


In [22]:
# 가변 크기 플레이스홀더
# 크기를 모를 때와 크기를 다양하게 받을 때
p = tf.placeholder(tf.int32, [None])
c = tf.constant(3)
x3_op = p * c
with tf.Session() as sess:
  res = sess.run(x3_op, feed_dict={p:[1,2,3]})
  print(res, type(res))
  res = sess.run(x3_op, feed_dict={p:[10,11]})
  print(res, type(res))

[3 6 9] <class 'numpy.ndarray'>
[30 33] <class 'numpy.ndarray'>


# 세션 구동

- Session()
- InteractiveSession()
  - run() 사용하지 않음
  - eval() 사용해 처리

In [0]:
sess = tf.InteractiveSession()

In [24]:
matrix1 = tf.constant([ [1., 2.], [3., 4.] ])
matrix2 = tf.constant([ [10.], [20.] ])
matrix1, matrix1.shape, matrix2, matrix2.shape

(<tf.Tensor 'Const_7:0' shape=(2, 2) dtype=float32>,
 TensorShape([Dimension(2), Dimension(2)]),
 <tf.Tensor 'Const_8:0' shape=(2, 1) dtype=float32>,
 TensorShape([Dimension(2), Dimension(1)]))

In [29]:
# 행렬의 곱
tf.matmul(matrix1, matrix2).eval()

array([[ 50.],
       [110.]], dtype=float32)

In [30]:
(matrix1 * matrix2).eval()

array([[10., 20.],
       [60., 80.]], dtype=float32)

In [0]:
sess.close()