# 개요

- 손쉽게 딥러닝을 할 수 있도록 다양한 엔진(플랫폼) 위에서 딥러닝 모델을 구현할 수 있는 API
- Tensorflow Dev SUMMIT 2017에서 케라스와 텐서플로우의 통합 발표
- tf.keras를 통해 케라스 사용
- 텐서플로우 코어 레이어와 케라스 레이어는 동일
- 모델 정의는 케라스의 고차원 API를 이용하여 구현

In [0]:
import keras
%tensorflow_version 1.x 

# 간단한 데이터

In [0]:
import numpy as np

In [4]:
# 데이터 준비
x = np.array([0,1,2,3,4])
# 인공신경망: 딥러닝의 알고리즘
# W-> 2 / b->1
y = x * 2 + 1
x, y

(array([0, 1, 2, 3, 4]), array([1, 3, 5, 7, 9]))

In [5]:
# 인공신경망: 층 쌓기
# 1. 인공신경망 모델을 만든다는 걸 파이썬 프로세스에게 알림
model = keras.models.Sequential()

In [6]:
# 2. 레이어 추가
# 입력 노드와 가중치가 1개씩인 선형 처리 계층
model.add(keras.layers.Dense(1, input_shape=(1,)))

In [7]:
# 3. 학습단계 설정
# optimizer=SGD(경사하강법) loss=mse(손실함수를 표현할 때 사용하는 평균제곱오차)
model.compile('SGD', 'mse')

In [8]:
# 훈련
# epochs: batch size, 학습 세대
# verbose: 로그, 학습 진행 사항을 표시(0이면 미표시)
model.fit( x[:2], y[:2], epochs=1000, verbose=0)

In [9]:
# 예측, 평가
model.predict(x[2:]).flatten()

array([4.9865932, 6.9768925, 8.967192 ], dtype=float32)

In [10]:
y[2:]

array([5, 7, 9])